name: DCO

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DCO Check
        uses: developer-guy/dco-action@v1.0.0
        with:
          target: ${{ github.event.pull_request.base.ref || github.ref_name }}